name: Run linters/fixers
on: [push]
jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        show-progress: false
    - uses: jbergstroem/hadolint-gh-action@2b00b87f8a56783930b6a4749837d7c45c567ff2  # v1.13.0
      with:
        dockerfile: '**/*Dockerfile'
        error_level: '1'  # Fail on warning or above.
